### ISSUE TITLE
WFLIB.LIB : fatal error LNK1136: 无效或损坏的文件

### ISSUE THREAD

**Issue by Alvin-gt** [6112562a/Ep_limited_cpp#1]
您好，我在win10的VS2017中使用的时候出现
**WFLIB.LIB : fatal error LNK1136: 无效或损坏的文件**
这个警告，尝试过使用官网的lib和您的lib都不行，
想请教一下这个问题该怎么解决呢？

**Comment by 6112562a** [comment]
下载安装MinGW:http://mingw.org/。
然后执行g++ -shared -o bdac.dll bdac.cpp classify.cpp rythmchk.cpp noisechk.cpp match.cpp postclas.cpp analbeat.cpp qrsfilt.cpp qrsdet2.cpp 编译出bdac.dll

**Comment by Alvin-gt** [comment]
> 下载安装MinGW:[http://mingw.org/。](http://mingw.org/%E3%80%82)
> 然后执行g++ -shared -o bdac.dll bdac.cpp classify.cpp rythmchk.cpp noisechk.cpp match.cpp postclas.cpp analbeat.cpp qrsfilt.cpp qrsdet2.cpp 编译出bdac.dll

按照这个成功生成了dll文件，多谢多谢
